# Generated by Django 3.0.7 on 2020-06-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='help', help_text='Write a description', max_length=100),
            preserve_default=False,
        ),
    ]
