# Generated by Django 3.0.7 on 2020-06-24 18:53

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='section',
        ),
        migrations.RemoveField(
            model_name='file',
            name='task',
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Task')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='homework',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='courses.Homework'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='students',
            field=models.ManyToManyField(through='courses.Homework', to=settings.AUTH_USER_MODEL),
        ),
    ]
