# Generated by Django 3.0.7 on 2020-06-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.FileField(default='', upload_to='images/courses/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
