# Generated by Django 3.0.7 on 2020-06-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200624_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
