# Generated by Django 3.0.7 on 2020-06-24 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_homework_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
