# Generated by Django 3.0.7 on 2020-06-24 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_delete_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Homework')),
            ],
        ),
    ]
