# Generated by Django 3.0.7 on 2020-06-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='graded',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
