# Generated by Django 3.0.7 on 2020-06-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20200625_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='graded',
            field=models.BooleanField(default=False),
        ),
    ]
