# Generated by Django 3.0.7 on 2020-06-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20200630_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(help_text='Format %Y-%m-%d %H:%M:%S'),
        ),
    ]
